site_name: CQP DNT Documentation
repo_url: https://github.com/agent-swyth/doc-cqp-dnt
repo_name: agent-swyth/doc-cqp-dnt

theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github-alt
  palette:
      primary: teal
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide

plugins:
  - search:
      lang:
        - fr
        - en
      separator: '[\s\-\.]'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - admonition

copyright: Copyright &copy; 2022 Agent-Swyth